spring.application.name=backend

# Подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dispatcher_db
spring.datasource.username=postgres
spring.datasource.password=maxsim12
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) настройки
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Логирование SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Settings
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# SMS Gateway 
sms.ru.api.url=https://sms.ru/sms/send
sms.ru.api.id=CE1E34D9-97FD-EE19-1F80-C6DB5A9E0BC2
# sms.ru.from=79197474282

server.address=0.0.0.0
